services:
  usersapi:
    container_name: UsersAPI
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: UsersAPI/Dockerfile
    depends_on: 
     - usersdb
    networks:
     - api

  usersdb:
    container_name: UsersDb
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Users25!"
    ports:
      - 14002:1433
    networks:
      - api

  redis:
    image: redis:latest
    restart: always
    ports:
      - "14005:6379"
    volumes:
      - /path/to/local/dаta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=Users25!
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
      
  ocelotapigw:
    container_name: OcelotGateway
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: OcelotAPIGw/Dockerfile
    ports:
        - 14000:8080
        - 14001:8081 
    networks:
     - api

volumes:
    redis-data:
    
networks:
    api:
     driver: bridge